/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SitemapDotxmlRouteImport } from './routes/sitemap[.]xml'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AuthenticatedRouteRouteImport } from './routes/_authenticated/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AuthenticatedWellnessRouteImport } from './routes/_authenticated/wellness'
import { Route as AuthenticatedTravelRouteImport } from './routes/_authenticated/travel'
import { Route as AuthenticatedSafetyRouteImport } from './routes/_authenticated/safety'
import { Route as AuthenticatedPregnancyRouteImport } from './routes/_authenticated/pregnancy'
import { Route as AuthenticatedMentorshipRouteImport } from './routes/_authenticated/mentorship'
import { Route as AuthenticatedMarketplaceRouteImport } from './routes/_authenticated/marketplace'
import { Route as AuthenticatedLibraryRouteImport } from './routes/_authenticated/library'
import { Route as AuthenticatedHealthRouteImport } from './routes/_authenticated/health'
import { Route as AuthenticatedExperienceRouteImport } from './routes/_authenticated/experience'
import { Route as AuthenticatedDashboardRouteImport } from './routes/_authenticated/dashboard'
import { Route as AuthenticatedCommunityRouteImport } from './routes/_authenticated/community'
import { Route as AuthenticatedCareersRouteImport } from './routes/_authenticated/careers'
import { Route as AuthenticatedTravelInboxRouteImport } from './routes/_authenticated/travel.inbox'
import { Route as AuthenticatedSettingsAppearanceRouteImport } from './routes/_authenticated/settings.appearance'

const SitemapDotxmlRoute = SitemapDotxmlRouteImport.update({
  id: '/sitemap.xml',
  path: '/sitemap.xml',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRouteRoute = AuthenticatedRouteRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedWellnessRoute = AuthenticatedWellnessRouteImport.update({
  id: '/wellness',
  path: '/wellness',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTravelRoute = AuthenticatedTravelRouteImport.update({
  id: '/travel',
  path: '/travel',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedSafetyRoute = AuthenticatedSafetyRouteImport.update({
  id: '/safety',
  path: '/safety',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedPregnancyRoute = AuthenticatedPregnancyRouteImport.update({
  id: '/pregnancy',
  path: '/pregnancy',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMentorshipRoute = AuthenticatedMentorshipRouteImport.update({
  id: '/mentorship',
  path: '/mentorship',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedMarketplaceRoute =
  AuthenticatedMarketplaceRouteImport.update({
    id: '/marketplace',
    path: '/marketplace',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)
const AuthenticatedLibraryRoute = AuthenticatedLibraryRouteImport.update({
  id: '/library',
  path: '/library',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedHealthRoute = AuthenticatedHealthRouteImport.update({
  id: '/health',
  path: '/health',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedExperienceRoute = AuthenticatedExperienceRouteImport.update({
  id: '/experience',
  path: '/experience',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedDashboardRoute = AuthenticatedDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCommunityRoute = AuthenticatedCommunityRouteImport.update({
  id: '/community',
  path: '/community',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedCareersRoute = AuthenticatedCareersRouteImport.update({
  id: '/careers',
  path: '/careers',
  getParentRoute: () => AuthenticatedRouteRoute,
} as any)
const AuthenticatedTravelInboxRoute =
  AuthenticatedTravelInboxRouteImport.update({
    id: '/inbox',
    path: '/inbox',
    getParentRoute: () => AuthenticatedTravelRoute,
  } as any)
const AuthenticatedSettingsAppearanceRoute =
  AuthenticatedSettingsAppearanceRouteImport.update({
    id: '/settings/appearance',
    path: '/settings/appearance',
    getParentRoute: () => AuthenticatedRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/careers': typeof AuthenticatedCareersRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/experience': typeof AuthenticatedExperienceRoute
  '/health': typeof AuthenticatedHealthRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/mentorship': typeof AuthenticatedMentorshipRoute
  '/pregnancy': typeof AuthenticatedPregnancyRoute
  '/safety': typeof AuthenticatedSafetyRoute
  '/travel': typeof AuthenticatedTravelRouteWithChildren
  '/wellness': typeof AuthenticatedWellnessRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/travel/inbox': typeof AuthenticatedTravelInboxRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/careers': typeof AuthenticatedCareersRoute
  '/community': typeof AuthenticatedCommunityRoute
  '/dashboard': typeof AuthenticatedDashboardRoute
  '/experience': typeof AuthenticatedExperienceRoute
  '/health': typeof AuthenticatedHealthRoute
  '/library': typeof AuthenticatedLibraryRoute
  '/marketplace': typeof AuthenticatedMarketplaceRoute
  '/mentorship': typeof AuthenticatedMentorshipRoute
  '/pregnancy': typeof AuthenticatedPregnancyRoute
  '/safety': typeof AuthenticatedSafetyRoute
  '/travel': typeof AuthenticatedTravelRouteWithChildren
  '/wellness': typeof AuthenticatedWellnessRoute
  '/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/travel/inbox': typeof AuthenticatedTravelInboxRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/_authenticated': typeof AuthenticatedRouteRouteWithChildren
  '/auth': typeof AuthRoute
  '/sitemap.xml': typeof SitemapDotxmlRoute
  '/_authenticated/careers': typeof AuthenticatedCareersRoute
  '/_authenticated/community': typeof AuthenticatedCommunityRoute
  '/_authenticated/dashboard': typeof AuthenticatedDashboardRoute
  '/_authenticated/experience': typeof AuthenticatedExperienceRoute
  '/_authenticated/health': typeof AuthenticatedHealthRoute
  '/_authenticated/library': typeof AuthenticatedLibraryRoute
  '/_authenticated/marketplace': typeof AuthenticatedMarketplaceRoute
  '/_authenticated/mentorship': typeof AuthenticatedMentorshipRoute
  '/_authenticated/pregnancy': typeof AuthenticatedPregnancyRoute
  '/_authenticated/safety': typeof AuthenticatedSafetyRoute
  '/_authenticated/travel': typeof AuthenticatedTravelRouteWithChildren
  '/_authenticated/wellness': typeof AuthenticatedWellnessRoute
  '/_authenticated/settings/appearance': typeof AuthenticatedSettingsAppearanceRoute
  '/_authenticated/travel/inbox': typeof AuthenticatedTravelInboxRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/careers'
    | '/community'
    | '/dashboard'
    | '/experience'
    | '/health'
    | '/library'
    | '/marketplace'
    | '/mentorship'
    | '/pregnancy'
    | '/safety'
    | '/travel'
    | '/wellness'
    | '/settings/appearance'
    | '/travel/inbox'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/auth'
    | '/sitemap.xml'
    | '/careers'
    | '/community'
    | '/dashboard'
    | '/experience'
    | '/health'
    | '/library'
    | '/marketplace'
    | '/mentorship'
    | '/pregnancy'
    | '/safety'
    | '/travel'
    | '/wellness'
    | '/settings/appearance'
    | '/travel/inbox'
  id:
    | '__root__'
    | '/'
    | '/_authenticated'
    | '/auth'
    | '/sitemap.xml'
    | '/_authenticated/careers'
    | '/_authenticated/community'
    | '/_authenticated/dashboard'
    | '/_authenticated/experience'
    | '/_authenticated/health'
    | '/_authenticated/library'
    | '/_authenticated/marketplace'
    | '/_authenticated/mentorship'
    | '/_authenticated/pregnancy'
    | '/_authenticated/safety'
    | '/_authenticated/travel'
    | '/_authenticated/wellness'
    | '/_authenticated/settings/appearance'
    | '/_authenticated/travel/inbox'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthenticatedRouteRoute: typeof AuthenticatedRouteRouteWithChildren
  AuthRoute: typeof AuthRoute
  SitemapDotxmlRoute: typeof SitemapDotxmlRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sitemap.xml': {
      id: '/sitemap.xml'
      path: '/sitemap.xml'
      fullPath: '/sitemap.xml'
      preLoaderRoute: typeof SitemapDotxmlRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/wellness': {
      id: '/_authenticated/wellness'
      path: '/wellness'
      fullPath: '/wellness'
      preLoaderRoute: typeof AuthenticatedWellnessRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/travel': {
      id: '/_authenticated/travel'
      path: '/travel'
      fullPath: '/travel'
      preLoaderRoute: typeof AuthenticatedTravelRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/safety': {
      id: '/_authenticated/safety'
      path: '/safety'
      fullPath: '/safety'
      preLoaderRoute: typeof AuthenticatedSafetyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/pregnancy': {
      id: '/_authenticated/pregnancy'
      path: '/pregnancy'
      fullPath: '/pregnancy'
      preLoaderRoute: typeof AuthenticatedPregnancyRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/mentorship': {
      id: '/_authenticated/mentorship'
      path: '/mentorship'
      fullPath: '/mentorship'
      preLoaderRoute: typeof AuthenticatedMentorshipRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/marketplace': {
      id: '/_authenticated/marketplace'
      path: '/marketplace'
      fullPath: '/marketplace'
      preLoaderRoute: typeof AuthenticatedMarketplaceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/library': {
      id: '/_authenticated/library'
      path: '/library'
      fullPath: '/library'
      preLoaderRoute: typeof AuthenticatedLibraryRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/health': {
      id: '/_authenticated/health'
      path: '/health'
      fullPath: '/health'
      preLoaderRoute: typeof AuthenticatedHealthRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/experience': {
      id: '/_authenticated/experience'
      path: '/experience'
      fullPath: '/experience'
      preLoaderRoute: typeof AuthenticatedExperienceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/dashboard': {
      id: '/_authenticated/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthenticatedDashboardRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/community': {
      id: '/_authenticated/community'
      path: '/community'
      fullPath: '/community'
      preLoaderRoute: typeof AuthenticatedCommunityRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/careers': {
      id: '/_authenticated/careers'
      path: '/careers'
      fullPath: '/careers'
      preLoaderRoute: typeof AuthenticatedCareersRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
    '/_authenticated/travel/inbox': {
      id: '/_authenticated/travel/inbox'
      path: '/inbox'
      fullPath: '/travel/inbox'
      preLoaderRoute: typeof AuthenticatedTravelInboxRouteImport
      parentRoute: typeof AuthenticatedTravelRoute
    }
    '/_authenticated/settings/appearance': {
      id: '/_authenticated/settings/appearance'
      path: '/settings/appearance'
      fullPath: '/settings/appearance'
      preLoaderRoute: typeof AuthenticatedSettingsAppearanceRouteImport
      parentRoute: typeof AuthenticatedRouteRoute
    }
  }
}

interface AuthenticatedTravelRouteChildren {
  AuthenticatedTravelInboxRoute: typeof AuthenticatedTravelInboxRoute
}

const AuthenticatedTravelRouteChildren: AuthenticatedTravelRouteChildren = {
  AuthenticatedTravelInboxRoute: AuthenticatedTravelInboxRoute,
}

const AuthenticatedTravelRouteWithChildren =
  AuthenticatedTravelRoute._addFileChildren(AuthenticatedTravelRouteChildren)

interface AuthenticatedRouteRouteChildren {
  AuthenticatedCareersRoute: typeof AuthenticatedCareersRoute
  AuthenticatedCommunityRoute: typeof AuthenticatedCommunityRoute
  AuthenticatedDashboardRoute: typeof AuthenticatedDashboardRoute
  AuthenticatedExperienceRoute: typeof AuthenticatedExperienceRoute
  AuthenticatedHealthRoute: typeof AuthenticatedHealthRoute
  AuthenticatedLibraryRoute: typeof AuthenticatedLibraryRoute
  AuthenticatedMarketplaceRoute: typeof AuthenticatedMarketplaceRoute
  AuthenticatedMentorshipRoute: typeof AuthenticatedMentorshipRoute
  AuthenticatedPregnancyRoute: typeof AuthenticatedPregnancyRoute
  AuthenticatedSafetyRoute: typeof AuthenticatedSafetyRoute
  AuthenticatedTravelRoute: typeof AuthenticatedTravelRouteWithChildren
  AuthenticatedWellnessRoute: typeof AuthenticatedWellnessRoute
  AuthenticatedSettingsAppearanceRoute: typeof AuthenticatedSettingsAppearanceRoute
}

const AuthenticatedRouteRouteChildren: AuthenticatedRouteRouteChildren = {
  AuthenticatedCareersRoute: AuthenticatedCareersRoute,
  AuthenticatedCommunityRoute: AuthenticatedCommunityRoute,
  AuthenticatedDashboardRoute: AuthenticatedDashboardRoute,
  AuthenticatedExperienceRoute: AuthenticatedExperienceRoute,
  AuthenticatedHealthRoute: AuthenticatedHealthRoute,
  AuthenticatedLibraryRoute: AuthenticatedLibraryRoute,
  AuthenticatedMarketplaceRoute: AuthenticatedMarketplaceRoute,
  AuthenticatedMentorshipRoute: AuthenticatedMentorshipRoute,
  AuthenticatedPregnancyRoute: AuthenticatedPregnancyRoute,
  AuthenticatedSafetyRoute: AuthenticatedSafetyRoute,
  AuthenticatedTravelRoute: AuthenticatedTravelRouteWithChildren,
  AuthenticatedWellnessRoute: AuthenticatedWellnessRoute,
  AuthenticatedSettingsAppearanceRoute: AuthenticatedSettingsAppearanceRoute,
}

const AuthenticatedRouteRouteWithChildren =
  AuthenticatedRouteRoute._addFileChildren(AuthenticatedRouteRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthenticatedRouteRoute: AuthenticatedRouteRouteWithChildren,
  AuthRoute: AuthRoute,
  SitemapDotxmlRoute: SitemapDotxmlRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
